### ISSUE TITLE
Bilder i prod hentes fra test

### ISSUE THREAD

**Issue by johannakinstad** [miles-no/conf.miles.no#37]
Får 404 error om man har et bilde i prod som ikke ligger i test, urlen tilsier at bildet hentes fra /test

**Comment by espen42** [comment]
Når man går til conf.miles.no, skjer det på et tidspunkt en sveltekit-initiert redirect til /konferanser:

```
Request URL: https://conf.miles.no/__data.json?x-sveltekit-invalidated=1_1
Request Method: GET
Status Code: 200 OK
```
...med body:
`{type: "redirect", location: "/konferanser"}`

Etter denne redirect'en hentes bilder fra test. 

Hvis man går direkte til conf.miles.no/konferanser, som også er det som skjer når man refresh'er etter redirect'en over, hentes bildene fra prod.

**Comment by espen42** [comment]
Duplikat? https://github.com/miles-no/conf.miles.no/issues/194
