### ISSUE TITLE
Bedre performance for cv partner api calls

### ISSUE THREAD

**Issue by johannakinstad** [miles-no/conf.miles.no#39]

**Comment by espen42** [comment]
Jeg lagde en primitiv cache for brukere pr kontor, for å løsne litt på dette: `crudeUsersByOfficeCache` i cvpartnerClient.ts. Fungerer i og for seg, men verdt å være oppmerksom på: oppdateres feks bare en gang i døgnet sånn det er satt opp nå, så nyansatte vil feks ikke dukke opp i lista med en gang. Og jeg har ikke testet den bredt; kan ikke utelukke at det fins bruksområder hos oss hvor den klaffer dårligere.
